[package]
name = "tp-holdem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.126", default-features = false, features = ["derive"] }
shuffle = { version = "0.1.7" }